### ISSUE TITLE
Source code in repo

### ISSUE THREAD

**Issue by ghost** [SlaveTEch/Uranium-Fortnite-Undetected-Cheat-With-Chest-ESP-Source-Leak#3]
Why u dont put sourecode in this repo?

**Comment by LeviRist** [comment]
> Why u dont put sourecode in this repo?

he literally explained it in the repo dumbass

**Comment by ghost** [comment]
github is platform to share sourcecodes not discord cdn links kekw. its doesnt matter how big source is

**Comment by LeviRist** [comment]
> github is platform to share sourcecodes not discord cdn links kekw. its doesnt matter how big source is

Who the fuck cares if it’s that big of a deal download it and upload it to your own repo
